### PR TITLE
New database sql

### PR DESCRIPTION
**Pull request by sumitsinghhazard**

### CODE REVIEW

**Comment by Arunsp2000** [comment]
I had a doubt regarding this, so we have a user type. What does userType actually denote? It can be doctor, Admin or Patient.
So do we have login options regarding this or something? Another thing is we have a user type here, but we also have doctors table separately as such. So if a new user wants to sign up as a doctor? Do I add the user to users table or doctor table?
Similarly for Admin, is there an admin table or something?
@sumitsinghhazard  @nitesh31mishra

**Comment by Arunsp2000** [comment]
Also ID is in varchar?
I guess we could do INT and autoincrement for it.
@sumitsinghhazard @nitesh31mishra

**Comment by sumitsinghhazard** [comment]
On ID to be autoincremented. Yes, lets do that

**Comment by sumitsinghhazard** [comment]
Now, we have all primary key ID as integer with auto increment. 
Also, the Doctor table now has a foreign key to the Users table.

**Comment by sumitsinghhazard** [comment]
@nitesh31mishra @Arunsp2000 let me know if you are both good with the changes. Can one of you complete the merge?

**Comment by Arunsp2000** [comment]
Changes look good, merged.

**Pull request merged**
