### PR TITLE
Add Doctor, Hospital API

### PR DESCRIPTION
**Pull request by nitesh31mishra**
I have added the routes for the doctor and hospital table

add (doctor, hospital)
update (doctor, hospital)
get info (doctor, hospital)
update(appointment)

Let me know in case of any changes.

### CODE REVIEW

**Comment by Arunsp2000** [comment]
Have given my comments, please check them out.
Only changes from my end seem to be isActive and approvalStatus.
Rest of the code looks good.
Let Sumit as well have a look.
@nitesh31mishra @sumitsinghhazard

**Comment by nitesh31mishra** [comment]
Yeah, I saw your comments on the other branch. Actually I deleted that branch and PR as well. I will mention the comments over here for reference. Thanks!

Isactive and approvalstatus we will setting it up initially 
isactive=True /// for add doctor and hospital
approvalstatus = False  /// for add doctot and hospital

**Comment by nitesh31mishra** [comment]
I have update the isactive and approvalstatus value in addDoctor and addHospital routes

**Comment by Arunsp2000** [comment]
> I have update the isactive and approvalstatus value in addDoctor and addHospital routes

Looks good to me then.
Can wait on @sumitsinghhazard and he can merge
 it

**Comment by nitesh31mishra** [comment]
I have added 2 APIs:
1. getDoctors - list of all doctors
2. getHospitals - list of all hospitals

Minor Fixes:
1. Login
2. Register
3. Speciality typo*
4. User length > 0 in the login

**Comment by nitesh31mishra** [comment]
Added the updated wolf care SQL file.

**Comment by Arunsp2000** [comment]
Changes look good
Merging

**Pull request merged**
