### PR TITLE
Feature/backend apis set s

### PR DESCRIPTION
**Pull request by sumitsinghhazard**
Added APIs after testing for:
Create affiliation
Update affiliation
Get affiliated hospitals for a doctor
Get affiliated doctors in a hospital
Search doctor
Search hospital
Create appointment

### CODE REVIEW

**Comment by sumitsinghhazard** [comment]
Also, updated SQL file to fix spellings of affiliationid in Affiliation and primaryspecialty in Doctors

**Review by nitesh31mishra — COMMENTED** [review]
Looks good!

**Comment by nitesh31mishra** [comment]
Can you add the new SQL file as well?

**Comment by Arunsp2000** [comment]
I feel each route in app.py should have the method ['OPTIONS'] in it.
Also new sql file can be posted.

**Comment by Arunsp2000** [comment]
One more question with regards to Admin. I had a discussion with Akash who said we can have a separate Admin table. This table, not sure of its contents can be manually added, I'm guessing just email and Password. Or better we can just use the User table and put Admin as the usertype?
@sumitsinghhazard @nitesh31mishra

**Comment by sumitsinghhazard** [comment]
ADMIN User: Can't think of any drawbacks to either of the approaches. Feel free to go with either of them.

**Comment by sumitsinghhazard** [comment]
Added the OPTIONS method to all APIs

**Comment by Arunsp2000** [comment]
Also if possible add the empty route.

**Comment by sumitsinghhazard** [comment]
yep, already there...

**Comment by Arunsp2000** [comment]
> ADMIN User: Can't think of any drawbacks to either of the approaches. Feel free to go with either of them.

Cool we can just keep a type at the moment which checks if he is an admin or not.

**Comment by sumitsinghhazard** [comment]
a separate column like "isadmin" ?

**Comment by sumitsinghhazard** [comment]
the existing usertype column

**Comment by Arunsp2000** [comment]
Changes look good!
Good to merge.

**Pull request merged**
